### ISSUE TITLE
Logo nav

### ISSUE THREAD

**Issue by Nidev-lab** [walterconticello/proyectofinal-front-grupo1#28]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Que al hacer click en el logo del nav se redirija a la pagina de inicio.

## Resultado actual

• Al hacer click no redirige a nungun sitio. 

## Captura

![image](https://github.com/walterconticello/proyectofinal-front-grupo1/assets/53904695/cf72fc6c-c3e0-4ea9-8ac0-337c149f0117)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by walterconticello** [comment]
Se corrigió el problema reportado
