### ISSUE TITLE
Botones sin accion

### ISSUE THREAD

**Issue by Nidev-lab** [walterconticello/proyectofinal-front-grupo1#29]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Que al hacer click en los botones redirijan a dicho lugar.

## Resultado actual

• Los botones no cumplen ninguna accion.

## Captura

![image](https://github.com/walterconticello/proyectofinal-front-grupo1/assets/53904695/75c51610-49f7-4fb4-b1f1-44d97ac6c362)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by walterconticello** [comment]
Se corrigió el problema reportado
