### ISSUE TITLE
Contacto

### ISSUE THREAD

**Issue by Nidev-lab** [walterconticello/proyectofinal-front-grupo1#30]
## Proceso

1. Ingrese a la pagina.
2. Llene el form de contacto.

## Resultado esperado

• Que no se permitan colocar numero ni signos en el nombre del usuario.
• Encontrar un max de caracteres a colocar en el mensaje.
• Un modal o alert que me avise que mi consulta fue enviada con exito. 

## Resultado actual

• Se permiten colocar numeros y signos en el nombre.
• Se pueden colocar caracteres infinitos en el mensaje.
• No hay un modal o un alert que me avise que mi consulta se envio

## Captura

![image](https://github.com/walterconticello/proyectofinal-front-grupo1/assets/53904695/e95c6ec4-2ff4-4e31-abd4-8efc13060432)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by marcosquinteros** [comment]
Se corrigió el problema reportado
