### ISSUE TITLE
Botones sin accion

### ISSUE THREAD

**Issue by Nidev-lab** [walterconticello/proyectofinal-front-grupo1#32]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Que al hacer click en los botones redirijan a dicho lugar.

## Resultado actual

•  Los botones no cumplen ninguna accion.

## Captura

![image](https://github.com/walterconticello/proyectofinal-front-grupo1/assets/53904695/b2ecd8bb-1766-4847-85d5-6368f4a5e3d6)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by walterconticello** [comment]
Se corrigió el problema reportado
