### ISSUE TITLE
Carrito

### ISSUE THREAD

**Issue by Nidev-lab** [walterconticello/proyectofinal-front-grupo1#33]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario.
3. Agregue uno pedidos al carrito.

## Resultado esperado

• No tener los productos cargados por otro usuario.

Ejemplo: Me logueo con Pepe1 agrego unos productos al carrito y cierro sesion, Luego me logueo con Juan1 y en mi carrito tengo los productos añadidos por Pepe1.

## Resultado actual

• Los productos cargados por otros usuarios aparecen cargados en los carritos de otros usuarios.

## Captura
Pepe1
![image](https://github.com/walterconticello/proyectofinal-front-grupo1/assets/53904695/45cdb857-074e-4cbe-88ef-340d11bf8f52)
![image](https://github.com/walterconticello/proyectofinal-front-grupo1/assets/53904695/9c48e38c-6d60-47f4-bb3f-e3dc6e905c3d)

Juan1
![image](https://github.com/walterconticello/proyectofinal-front-grupo1/assets/53904695/d209c0de-f301-4a4f-8a2f-06139a615df2)
![image](https://github.com/walterconticello/proyectofinal-front-grupo1/assets/53904695/8e78c8f5-c2b9-4b00-a806-6f82106a0f58)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by marcosquinteros** [comment]
Se corrigió el problema reportado
